batch_size: 1024
epochs: 40
eval_every_n_epochs: 1
fine_tune_from: mmargin_lr0.3
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
mode: eval

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (32,32,3)
  num_workers: 8
  valid_size: 0.05

loss:
  semi_hard : Yes
  mode : nt-logistic
  temperature: 0.5
  use_cosine_similarity: True
